### ISSUE TITLE
wrong parameter data type of getHistoricQuotes

### ISSUE THREAD

**Issue by liulinglll** [mainstringargs/alpaca-java#14]
the data type of "offset" of getHistoricQuotes(String symbol, LocalDate date, Integer offset, Integer limit) should be Long as its milliseconds. please fix it. thanks

**Comment by mainstringargs** [comment]
Strange, I'll take a look.  It's based on the PolygonAPI which has Integer listed as the parameter type:  https://polygon.io/docs/#!/Stocks--Equities/get_v1_historic_quotes_symbol_date

**Comment by mainstringargs** [comment]
Interesting -- I guess its an error in the Polygon documentation.  I've updated and released 4.0.1.  Take a look.
