### ISSUE TITLE
Polygon API getHistoricQuotes() implemented incorrectly

### ISSUE THREAD

**Issue by artur-tamazian** [mainstringargs/alpaca-java#34]
getHistoricQuotes() method body and signature seem wrong. Looks like it was copied from getHistoricTrades() as is and returns wrong data.

**Comment by mainstringargs** [comment]
Thanks for the tip, will look into it

**Comment by artur-tamazian** [comment]
Nevermind, I missed the difference between these methods bodies. Seems correct to me now.
