### ISSUE TITLE
LastQuoteResponse.last is an ArrayList

### ISSUE THREAD

**Issue by mainstringargs** [mainstringargs/alpaca-java#35]
In the schema it is set up like this:

```
    "last": {
      "existingJavaType": "java.util.ArrayList<io.github.mainstringargs.domain.polygon.lastquote.LastQuote>",
      "title": "last"
    }
```

But last in the documentation is an object:

https://polygon.io/docs/#!/Stocks--Equities/get_v1_last_quote_stocks_symbol

**Comment by mainstringargs** [comment]
@Petersoj  Can you take a quick look at this and tell me if you agree?  @artur-tamazian  pointed this out in slack

**Comment by Petersoj** [comment]
@mainstringargs You are correct. #36 fixes this.
