### ISSUE TITLE
polygon.domain classes missing from source

### ISSUE THREAD

**Issue by 5toner** [mainstringargs/alpaca-java#4]
I just downloaded the source and the PolygonAPI won't compile because the polygon.domain package is missing...

```
import io.github.mainstringargs.polygon.domain.SymbolAnalystRatings;
import io.github.mainstringargs.polygon.domain.SymbolDetails;
import io.github.mainstringargs.polygon.domain.SymbolDividend;
import io.github.mainstringargs.polygon.domain.SymbolEarning;
import io.github.mainstringargs.polygon.domain.SymbolEndpoints;
import io.github.mainstringargs.polygon.domain.SymbolFinancial;
import io.github.mainstringargs.polygon.domain.SymbolNews;
import io.github.mainstringargs.polygon.domain.Ticker;
```

I also noticed other domain package classes missing like...

```
import io.github.mainstringargs.polygon.domain.StockQuote;
import io.github.mainstringargs.polygon.domain.StockTrade;
```
Should I this pull this from another repository?  Or should it be in this one?

**Comment by mainstringargs** [comment]
These files are generated from the json files in the sampleJson folder using jsonShema2Pojo.  Running “gradlew build” will create the source.

**Comment by 5toner** [comment]
Thank you for the prompt response.  Sorry I overlooked this detail as I’m
using Maven.

**Comment by mainstringargs** [comment]
No problem.  Thanks for taking a look.
