### ISSUE TITLE
Alpaca.properties Question

### ISSUE THREAD

**Issue by josht000** [mainstringargs/alpaca-java#40]
What is the user_agent property? I'm familiar with the key_id and secret_key, but where do I find user_agent_key??

Thanks

**Comment by Petersoj** [comment]
You can leave that property blank as it will be automatically set to the default found [here](https://github.com/mainstringargs/alpaca-java/blob/master/src/main/resources/alpaca.properties.default).

**Comment by josht000** [comment]
Ok, thanks.
