### ISSUE TITLE
getExchanges() returns MarketHoliday

### ISSUE THREAD

**Issue by drse** [mainstringargs/alpaca-java#46]
See https://github.com/mainstringargs/alpaca-java/blob/master/src/main/java/io/github/mainstringargs/polygon/PolygonAPI.java#L474

Should return Exchange instead

**Comment by Petersoj** [comment]
Oops. That's kinda embarrassing lol. PR https://github.com/mainstringargs/alpaca-java/pull/47 fixes this. It'll be merged sometime next week probably. Thanks for reporting this!

**Comment by mainstringargs** [comment]
Will get it released on friday

**Comment by mainstringargs** [comment]
Implemented in 5.0.7
