### ISSUE TITLE
Could not find method buildScan() for arguments

### ISSUE THREAD

**Issue by 5toner** [mainstringargs/alpaca-java#5]
I ran...

> gradlew build

And got...

> Could not find method buildScan() for arguments

I edited the build.gradle and added the if statement below to get it to work...

```
if (hasProperty('buildScan')) {
	buildScan { licenseAgreementUrl = 'https://gradle.com/terms-of-service'; licenseAgree = 'yes' }
}
```

Might want to update the codebase.

**Comment by mainstringargs** [comment]
Updated
