### ISSUE TITLE
Undefined classes

### ISSUE THREAD

**Issue by laviRZ** [mainstringargs/alpaca-java#51]
Classes:
AlpacaStreamMessage
TradeUpdateMessage
AccountUpdateMessage
AlpacaStreamMessage

are not defined...

**Comment by mainstringargs** [comment]
Where are you seeing that?  On maven central or from 'releases' here?  I may have uploaded a bad compile.

**Comment by mainstringargs** [comment]
Or actually -- what version of the API are you using?  Things have moved around in the past couple of months

**Comment by mainstringargs** [comment]
For the classes you reference, they are in the javadoc -- please verify things on your end, and if they still look wrong, I'll try to figure out what is going on:

https://javadoc.io/static/io.github.mainstringargs/alpaca-java/5.0.8/io/github/mainstringargs/domain/alpaca/websocket/AlpacaStreamMessage.html
https://javadoc.io/static/io.github.mainstringargs/alpaca-java/5.0.8/io/github/mainstringargs/domain/alpaca/websocket/trade/TradeUpdateMessage.html
https://javadoc.io/static/io.github.mainstringargs/alpaca-java/5.0.8/io/github/mainstringargs/domain/alpaca/websocket/account/AccountUpdateMessage.html
https://javadoc.io/static/io.github.mainstringargs/alpaca-java/5.0.8/io/github/mainstringargs/domain/alpaca/websocket/AlpacaStreamMessage.html

**Comment by laviRZ** [comment]
io.github.mainstringargs.domain appears to be missing

**Comment by mainstringargs** [comment]
Are you building this yourself or using jars?  If you're building it yourself, you have to do a ./gradlew build to generate those classes.  They will appear in build/generated-sources/schemajson

**Comment by laviRZ** [comment]
I downloaded it from github, and opened using IntelliJ.

**Comment by mainstringargs** [comment]
Ok -- i haven't been using intellij, so it may take some tweaking to get it intellij friendly -- for eclipse, there is an eclipse target that generates the eclipse config.  I know for certain though, you will need to do a "gradlew build" to generate the json related classes, and add them to your intellij classpath.

**Comment by laviRZ** [comment]
Okay, it is working now, but I don't understand why the domain classes aren't in the github

**Comment by mainstringargs** [comment]
They are generated
