### ISSUE TITLE
Watchlist 

### ISSUE THREAD

**Issue by laviRZ** [mainstringargs/alpaca-java#52]
When running the example program, you get 

`io.github.mainstringargs.alpaca.rest.exception.AlpacaAPIRequestException: Alpaca API Request Exception! : Status Code = 422, Status Text = "Unprocessable Entity", API Response Code = 40010001, API Response Message = "watchlist name must be unique"
	at io.github.mainstringargs.alpaca.AlpacaAPI.createWatchlist(AlpacaAPI.java:1121)
	at com.lavirz.alpaca.AlpacaExample.main(AlpacaExample.java:69)`

**Comment by Petersoj** [comment]
Look at the error message: `watchlist name must be unique`
The example program shouldn't necessarily be run in whole by the way. It's simply to show you some example code snippets.

**Comment by laviRZ** [comment]
okay.
unrelated: how to I get an asstet's value?

**Comment by Petersoj** [comment]
[Here](https://javadoc.io/doc/io.github.mainstringargs/alpaca-java/latest/io/github/mainstringargs/alpaca/AlpacaAPI.html#getAssetBySymbol-java.lang.String-)
I would also encourage you ask these types of questions in the Alpaca Slack channel #dev-alpaca-java where we can have more of a discussion and close this issue :)

**Comment by laviRZ** [comment]
Sorry, not very familiar with the system:)

**Comment by Petersoj** [comment]
No worries :)

**Comment by laviRZ** [comment]
how do I join the slack?
